name: blog_dev
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - amqp=2.6.1
  - autopep8=1.5.7
  - backcall=0.2.0
  - billiard=3.6.4.0
  - ca-certificates=2021.7.5
  - celery=5.0.5
  - certifi=2021.5.30
  - cffi=1.14.6
  - click=7.1.2
  - click-didyoumean=0.0.3
  - click-plugins=1.1.1
  - click-repl=0.2.0
  - cryptography=3.4.7
  - decorator=5.0.9
  - future=0.18.2
  - greenlet=1.1.0
  - gunicorn=20.1.0
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - kombu=4.6.11
  - libffi=3.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mysql-connector-c=6.1.11
  - mysqlclient=2.0.3
  - ncurses=6.2
  - openssl=1.1.1k
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - python=3.8.10
  - pytz=2021.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - tk=8.6.10
  - toml=0.10.2
  - traitlets=5.0.5
  - vine=1.3.0
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - django==1.11.29
    - django-grappelli==2.10.4
    - django-redis==4.9.0
    - hiredis==0.2.0
    - marko==1.1.0
    - redis==2.10.6
